#!/bin/sh
# tpgxyz@gmail.com

if grep -q '\bsystemd.unit=calamares.target\b' /proc/cmdline; then
    if [ -x /usr/bin/startx ] && [ -x /usr/sbin/calamares-install-setup ]; then
	/usr/bin/startx /usr/sbin/calamares-install-setup $* -- -dpi 96 vt1 -background none
    else
	echo "calamares-install-setup: critical programs are missing, check you system!"
	sleep 30
	reboot
    fi
fi
