#!/bin/sh
# tpgxyz@gmail.com

errorCatch() {
    printf '%s\n' "Something went wrong. Exiting in 30 seconds."
    sleep 30
# using -i forces reboot in case of using systemd-inhibit
    /bin/systemctl -i reboot
}

trap errorCatch ERR SIGHUP SIGINT SIGTERM

if grep -q '\bsystemd.unit=calamares.target\b' /proc/cmdline; then
    source /etc/locale.conf

# ensure plymouth really has stopped
    if pgrep "plymouthd" > /dev/null 2>&1; then
	/bin/plymouth quit --retain-splash
    fi

    /bin/systemctl stop crond.service &

    xset -dpms
    xset s off
# (tpg) fix VirtualBox screen too small for calamares in install mode 
    grep -iq "VirtualBox" "/sys/devices/virtual/dmi/id/product_name" && xrandr -s 1024x768

# openbox config file to start clamares window undecorated and maximized in install mode
    mkdir -p /root/.config/openbox
    cp -fa /etc/xdg/openbox/rc.xml /etc/xdg/openbox/rc-install.xml
    sed -i -e '/<\/applications>/ i \
  <application name="calamares" \
               class="Calamares" \
               title="OpenMandriva Lx Installer" \
               type="normal"> \
    <decor>no</decor> \
    <focus>yes</focus> \
    <fullscreen>yes</fullscreen> \
    <!--maximized>true</maximized--> \
  </application>' /etc/xdg/openbox/rc-install.xml

    if [ -x /usr/bin/openbox ]; then
	/usr/bin/openbox --config-file /etc/xdg/openbox/rc-install.xml &
    else
	echo "openbox not found. Exiting."
	sleep 30
	/bin/systemctl -i reboot
    fi

    sleep 2

    if [ "$(pidof openbox)" ]; then
# setup background
	if [ -e /usr/share/mdk/backgrounds/default.png ] && [ -f /usr/bin/xloadimage ]; then
	    /usr/bin/xloadimage -onroot -fullscreen /usr/share/mdk/backgrounds/default.png &
	fi
# use systemd-inhibit to be sure installation process won't be killed by users mistake
	/bin/systemd-inhibit --why="Running calamares" /usr/bin/calamares
	sleep 2
	if [ $? != 0 ]; then
	    errorCatch
	fi
    else
	printf '%s\n' "openbox is not running. Rebooting..."
	sleep 5
    fi

# check if we are booted from cd/dvd-rom to eject it
    blkid /dev/sr0 >/dev/null 2>&1
    if [ $? = '0' ]; then
	eject
	sleep 30
    fi

    sync
    systemctl -i reboot

fi
